# Generated by Django 3.1.7 on 2021-04-07 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(default='btao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_requests_approved', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_approved',
            field=models.DateField(null=True, verbose_name='date_approved'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Unapproved'), (2, 'Created')], default=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
