# Generated by Django 3.1.7 on 2021-04-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.agreement')),
                ('new_first_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_new_f', to='notice.first_notice')),
                ('new_per_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_new_p', to='notice.periodical_notice')),
                ('old_first_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_old_f', to='notice.first_notice')),
                ('old_per_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_old_p', to='notice.periodical_notice')),
            ],
        ),
    ]
