# Generated by Django 3.1.7 on 2021-03-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_contract_approved_by_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_released', models.DateField(verbose_name='date released')),
                ('payment_start_date', models.DateField(verbose_name='payment start date')),
                ('payment_end_date', models.DateField(verbose_name='payment end date')),
                ('notice_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
    ]
