# Generated by Django 3.1.7 on 2021-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_notice',
            name='cname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='deadline',
            field=models.DateField(null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='loc_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='rent',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment_notice',
            name='date_released',
            field=models.DateField(auto_now_add=True),
        ),
    ]
