# Generated by Django 3.1.7 on 2021-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210315_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_notice',
            old_name='rent',
            new_name='promotion_fee',
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='payment_cycle',
            field=models.IntegerField(default=3, verbose_name='payment cycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='total_rent',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
