# Generated by Django 3.1.7 on 2021-03-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210316_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_notice',
            name='promotion_fee',
        ),
        migrations.RemoveField(
            model_name='payment_notice',
            name='total_rent',
        ),
    ]
