# Generated by Django 3.1.7 on 2021-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210316_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_notice',
            name='promotion_fee',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payment_notice',
            name='total_rent',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
