# Generated by Django 3.1.7 on 2021-03-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_approved_by_manager'),
        ('payment', '0005_auto_20210316_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_Notice',
            new_name='First_Payment_Notice',
        ),
    ]
