# Generated by Django 3.1.7 on 2021-03-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210322_0813'),
        ('payment', '0006_auto_20210322_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodical_Payment_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_released', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(null=True, verbose_name='deadline')),
                ('payment_start_date', models.DateField(verbose_name='payment start date')),
                ('payment_end_date', models.DateField(verbose_name='payment end date')),
                ('notice_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('loc_code', models.CharField(max_length=200, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('period_num', models.IntegerField(verbose_name='period_num')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
