# Generated by Django 3.1.7 on 2021-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_periodical_payment_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodical_payment_notice',
            name='date_released',
            field=models.DateField(verbose_name='date_released'),
        ),
    ]
