# Generated by Django 3.1.7 on 2021-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210325_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_payment_notice',
            name='date_payed',
            field=models.DateField(null=True, verbose_name='date_payed'),
        ),
        migrations.AddField(
            model_name='periodical_payment_notice',
            name='date_payed',
            field=models.DateField(null=True, verbose_name='date_payed'),
        ),
    ]
