# Generated by Django 3.1.7 on 2021-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20210325_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_payment_notice',
            name='hcity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='first_payment_notice',
            name='hname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='periodical_payment_notice',
            name='hcity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='periodical_payment_notice',
            name='hname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
