# Generated by Django 3.1.7 on 2021-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20210327_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_payment_notice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='periodical_payment_notice',
            name='is_active',
        ),
        migrations.AddField(
            model_name='first_payment_notice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Overdue'), (2, 'Payed')], default=0),
        ),
        migrations.AddField(
            model_name='periodical_payment_notice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Overdue'), (2, 'Payed')], default=0),
        ),
    ]
