# Generated by Django 3.1.7 on 2021-03-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_id', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('core_business', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('sign_date', models.DateField(verbose_name='sign date')),
                ('floor_num', models.IntegerField(verbose_name='floor number')),
                ('store_loc_code', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('area', models.DecimalField(decimal_places=3, max_digits=20)),
                ('monthly_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('yearly_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('payment_cycle', models.IntegerField(verbose_name='payment cycle')),
                ('business', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=200)),
                ('promotion_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('deposit', models.DecimalField(decimal_places=3, max_digits=20)),
                ('perf_bond', models.DecimalField(decimal_places=3, max_digits=20)),
                ('water_bill', models.DecimalField(decimal_places=3, max_digits=20)),
                ('elect_bill', models.DecimalField(decimal_places=3, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.company')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
