# Generated by Django 3.1.7 on 2021-03-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='company',
            name='core_business',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_address',
            field=models.CharField(max_length=2000),
        ),
    ]
