# Generated by Django 3.1.7 on 2021-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210309_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
