# Generated by Django 3.1.7 on 2021-03-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_approved_by_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=2000)),
                ('owner_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='company',
            new_name='buyer_company',
        ),
        migrations.AddField(
            model_name='contract',
            name='host_company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contracts.host'),
        ),
    ]
