# Generated by Django 3.1.7 on 2021-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20210323_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='未审核通过', max_length=13),
        ),
    ]
