# Generated by Django 3.1.7 on 2021-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In Review'), (2, 'Approved'), (3, 'Unapproved'), (4, 'Completed')], default=0),
        ),
    ]
