# Generated by Django 3.1.7 on 2021-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20210330_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='无编号（未审核通过）', max_length=13),
        ),
    ]
