# Generated by Django 3.1.7 on 2021-04-02 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0011_auto_20210330_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_by',
            field=models.ForeignKey(default='btao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_requests_approved', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_approved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_approved'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
