# Generated by Django 3.1.7 on 2021-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20210428_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='to_be_payed',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
