# Generated by Django 3.1.7 on 2021-04-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0011_auto_20210330_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodical_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(null=True, verbose_name='deadline')),
                ('payment_start_date', models.DateField(verbose_name='payment start date')),
                ('payment_end_date', models.DateField(verbose_name='payment end date')),
                ('notice_id', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Overdue'), (2, 'Payed')], default=0)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('hname', models.CharField(max_length=200, null=True)),
                ('hcity', models.CharField(max_length=200, null=True)),
                ('loc_code', models.CharField(max_length=200, null=True)),
                ('date_payed', models.DateField(null=True, verbose_name='date_payed')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('period_num', models.IntegerField(verbose_name='period_num')),
                ('date_released', models.DateField(verbose_name='date_released')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='First_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(null=True, verbose_name='deadline')),
                ('payment_start_date', models.DateField(verbose_name='payment start date')),
                ('payment_end_date', models.DateField(verbose_name='payment end date')),
                ('notice_id', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Overdue'), (2, 'Payed')], default=0)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('hname', models.CharField(max_length=200, null=True)),
                ('hcity', models.CharField(max_length=200, null=True)),
                ('loc_code', models.CharField(max_length=200, null=True)),
                ('date_payed', models.DateField(null=True, verbose_name='date_payed')),
                ('promotion_fee', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('payment_cycle', models.IntegerField(verbose_name='payment cycle')),
                ('total_rent', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('date_released', models.DateField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
