# Generated by Django 3.1.7 on 2021-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_notice',
            name='promotion_fee',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='first_notice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='first_notice',
            name='total_rent',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='periodical_notice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
