# Generated by Django 3.1.7 on 2021-04-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0015_auto_20210428_0559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0004_auto_20210428_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_requests_created', to=settings.AUTH_USER_MODEL)),
                ('new_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_new', to='contracts.contract')),
                ('old_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_old', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement')),
                ('new_first_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_new_f', to='notice.first_notice')),
                ('new_per_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_new_p', to='notice.periodical_notice')),
                ('old_first_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_old_f', to='notice.first_notice')),
                ('old_per_notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_pair_old_p', to='notice.periodical_notice')),
            ],
        ),
    ]
