# Generated by Django 3.1.7 on 2021-04-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_pair',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice_pair',
            name='is_per',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice_pair',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement'),
        ),
    ]
