# Generated by Django 3.1.7 on 2021-04-30 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_auto_20210428_0700'),
        ('agreements', '0003_auto_20210430_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='text',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='new_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_new', to='contracts.contract'),
        ),
    ]
